system("java -version")
packageVersion("sparklyr")
install.packages("sparklyr")
library(sparklyr)
spark_install("2.3")
spark_available_versions()
spark_install(version = "1.6")
spark_installed_versions()
spark_uninstall(version = "1.6.3", hadoop = "2.6")
library(sparklyr)
sc <- spark_connect(master = "local", version = "2.3")